### ISSUE TITLE
Error `deno task dev` (and others) commands when try to use `vite-extra` with react

### ISSUE THREAD

**Issue by kindkitchen** [bartlomieju/vite-deno-example#9]
```js
Task dev deno run -A --unstable --node-modules-dir npm:vite
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getReport')
    at isMusl (file:///home/t/deno_forge/_hft3/deno_ui/node_modules/.deno/rollup@4.6.0/node_modules/rollup/dist/native.js:5:30)
    at getPackageBase (file:///home/t/deno_forge/_hft3/deno_ui/node_modules/.deno/rollup@4.6.0/node_modules/rollup/dist/native.js:53:28)
    at Object.<anonymous> (file:///home/t/deno_forge/_hft3/deno_ui/node_modules/.deno/rollup@4.6.0/node_modules/rollup/dist/native.js:28:21)
    at Object.<anonymous> (file:///home/t/deno_forge/_hft3/deno_ui/node_modules/.deno/rollup@4.6.0/node_modules/rollup/dist/native.js:81:4)
    at Module._compile (node:module:733:34)
    at Object.Module._extensions..js (node:module:747:10)
    at Module.load (node:module:658:32)
    at Function.Module._load (node:module:539:12)
    at Module.require (node:module:677:19)
    at require (node:module:791:16)
```

Is it possible to fix this or may be I made something wrong (however I only run `deno run -A npm:create-vite-extra@lates`)?
Thanks)

**Comment by kindkitchen** [comment]
![image](https://github.com/bartlomieju/vite-deno-example/assets/53253722/570f226f-d472-415d-b10f-6c23b13469f5)

This remove issue. So I suppose my operation system is not recognized correctly or something like this...
With this hardcoded `false` value for `isMusl()` all is worked. But hope the better solution is exists.
Thanks)

**Comment by nik-kita** [comment]
Deno 1.39.0 fix this issue, thanks!)

**Comment by kindkitchen** [comment]
Deno 1.39.0 fix this issue, thanks!)
